#!/usr/bin/env bash
#--------------------------------------------------------
# Script     :
# Descrição  :
# Versão     : 0.1
# Autor      : Leandro Höher <leandrohoher75@outlook.com
# Data       : 17/01/2026 
# Licença    : GNU/GLP v3.0
#-------------------------------------------------------- 
# Uso:
#--------------------------------------------------------
mpv "https://youtube.com/playlist?list=PLXoSGejyuQGqJEEyo2fY3SA-QCKlF2rxO&si=n29h80f_VwIiefOm"
