#!/usr/bin/env bash

# Testa se usuário passou o número certo de argumentos... (1 argumento)

# Opções...

editor="nano"

# Variáveis

dia_de_hoje=$( date +'%d/%m/%Y' )

header="#!/usr/bin/env bash
#--------------------------------------------------------
# Script     :
# Descrição  :
# Versão     : 0.1
# Autor      : Leandro Höher <leandrohoher75@outlook.com
# Data       : $dia_de_hoje 
# Licença    : GNU/GLP v3.0
#-------------------------------------------------------- 
# Uso:
#--------------------------------------------------------
"
# Testa se usuário passou o número certo  de argumentos... (1  Argumento)
 
[[ $# -ne 1 ]] && echo "É preciso de *um* nome de arquivo!" && exit 1

# Testa  se arquivo já existe...

[[ -f $1 ]] && echo " Atenção: Este arquivo já existe! Saindo!" && exit 1

echo "$header" > $1
chmod +x $1
$editor  $1

exit 0

