#!/usr/bin/env bash
#--------------------------------------------------------
# Script     :EStrutura de menu
# Descrição  :
# Versão     : 0.1
# Autor      : Leandro Höher <leandrohoher75@outlook.com
# Data       : 24/12/2025 
# Licença    : GNU/GLP v3.0
#-------------------------------------------------------- 
# Uso:
#--------------------------------------------------------


clear

fruta=(banana laranja abacate)

while true; do

      clear

      echo "1. Banana"
      echo "2. Laranja"
      echo "3. abacate"
      echo "4. Sair"
      read -p "Escolha o número da sua opção: " opt

      [[ $opt -eq 4 ]] && break
      echo "Você escolheu ${fruta[$(( $opt -1 ))]}."

      read -p "Tecle algo para continuar..." continua

done
